%% CIC Filter
% Source: https://ch.mathworks.com/help/dsp/ref/fdesign.ciccomp.html
% clear all;close all;clc;
% fs = 96e3;   % Input sampling frequency.
% fpass = 4e3; % Frequency band of interest.
% m = 6;  % Decimation factor.
% hcic = design(fdesign.decimator(m,'cic',1,fpass,60,fs),'SystemObject',true);
% hd = design(fdesign.ciccomp(hcic.DifferentialDelay, ...
%             hcic.NumSections,fpass,4.5e3,.1,60,fs/m),'SystemObject',true);
% fvtool(hcic,hd,...
%     cascade(hcic,hd),'ShowReference','off','Fs',[96e3 96e3/m 96e3])
%     legend('CIC Decimator','CIC Compensator','Resulting Cascade Filter');
    
%% Own Implementation
clear all;close all;
M = 1;
R = 8;
fc = 0.5; % relative to first null of CIC
Fpcic = fc * 1/R;
Ast = 60;
Fpcfir = fc;
Fstcfir = Fpcfir * 4/3;
Astcfir = 60;
Apcfir = 0.01;
dcic = fdesign.decimator(R,'cic',M,Fpcic,Ast);
Hcic = design(dcic,'SystemObject',true);
dcfir = fdesign.ciccomp(Hcic.DifferentialDelay,...
        Hcic.NumSections,'fp,fst,ap,ast',Fpcfir,Fstcfir,Apcfir,Astcfir);
Hcfir = design(dcfir,'SystemObject',true);
% fvtool(Hcic,Hcfir,'Fs',[1*R 1]);

%% Store results
[H,w] = freqz(Hcic,4e3);
plotFile = 'cfirDemoCICAlone.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
[H,wcfir] = freqz(Hcfir,500);
H = [H' fliplr(H')]';
H = [H' fliplr(H')]';
H = [H' fliplr(H')]';
plotFile = 'cfirDemoCFIRAlone.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
[H,w] = freqz(cascade(Hcic,Hcfir),4e3);
plotFile = 'cfirDemoCascade.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
w = (0:pi/(1e3*10):pi/10)';
H = freqz(Hcic,w);
H = H ./ max(abs(H));
plotFile = 'cfirDemoCICAlonePBDetail.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
H = freqz(Hcfir,w);
H = H ./ max(abs(H));
plotFile = 'cfirDemoCFIRAlonePBDetail.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
H = freqz(cascade(Hcic,Hcfir),w);
H = H ./ max(abs(H));
plotFile = 'cfirDemoCascadePBDetail.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);