clear all;close all;clc;

% https://ch.mathworks.com/help/dsp/ref/fdesign.ciccomp.html

fs     = 125e6;    % Input sampling frequency.
fpass  = 48e3;     % Frequency band of interest. (End of Pass Band)
f_stop = 50e3;     % Start of Stop Band
R      = 650;      % Decimation factor.
sbA    = 10;       % Stop band attenuation
M      = 1;        % Differential Delay

hcic = design(fdesign.decimator(R,'cic',M,fpass,sbA,fs),'SystemObject',true);

hcomp = design(...
    fdesign.ciccomp(...
        hcic.DifferentialDelay, ...
        hcic.NumSections,...
        fpass,...
        f_stop,...
        .1,...
        sbA,...
        fs/R...
    ),'SystemObject',true);


fvtool(hcic,hcomp,...
cascade(hcic,hcomp),'ShowReference','off','Fs',[fs fs/R fs])

legend('CIC Decimator','CIC Compensator','Resulting Cascade Filter');