# ---------------------------------------------------------------------------- #
# Makefile for FPGA Filter Resource Testing
#
# Makefile for design/fpga/
# Location:    design/fpga/Makefile
#
# Authors: Raphael Frey <rmfrey@alpenwasser.net>
#
# Date:   2017-06-20
#
# Called by: user
#
# Working Directory: design/fpga/
# ---------------------------------------------------------------------------- #
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-205--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-205--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-205--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-210--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-215--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-225--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-230--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-235--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-240--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-245--ap-999--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-010--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-010--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-010--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-010--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-100--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-100--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-100--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-100--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-200--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-200--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-200--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-200--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-250--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-250--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-250--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-250--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-500--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-500--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-500--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-500--ast-80.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-999--ast-100.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-999--ast-40.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-999--ast-60.coe
#$(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-250--ap-999--ast-80.coe
COE_FILE ?= $(shell pwd)/../filter/coefData/decFIR/r-005--fp-200--fst-220--ap-250--ast-60.coe
VIVADO := vivado -nolog -nojournal -mode batch

RM := rm -f
RMR := rm -rf

.DEFAULT: all

all:
	$(VIVADO) -source vivadoDispatcher.tcl

decFIR:
	$(VIVADO) -source filters.tcl -tclargs $(COE_FILE)

clean:
	$(RM) *.log
	$(RM) *.jou
	$(RMR) tmp
