%%
clear all; close all; clc;
fs = 125e6; T = 1/fs;
N = 2^9;
R = 5;
e = 0.85;
fp = (fs/R*e/2);

[Ord, Wp] = ellipord(e/R, (1/e)/R, 1, 60 );
[B, A] = ellip(Ord, 1, 60, fp/(fs/2));

[H, w] = freqz(B, A, R*N+1);

Hr = reshape(H(2:end), N, R)';
Hr(2:2:end, :) = Hr(2:2:end, end:-1:1);

wr = w(2:N+1);
Hrtot = max(abs(Hr(2:end, :)));

% figure;
% plot(w, 20*log10(abs(H)), '-k', wr, 20*log10(abs(Hr(2:end, :)))', wr, 20*log10(Hrtot), '-k','LineWidth', 2); grid on

% figure;
% plot(w, 20*log10(abs(H)), '-b', wr, 20*log10(Hrtot), '-r','LineWidth', 2); grid on

%% Save to files
plotFile = 'iirAliasingCleanZero.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(H) w],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingCleanP2.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(Hr(2,1:N))' (wr(1:N))],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingCleanN2.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(Hr(3,1:N))' (wr(1:N))],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingCleanP4.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(Hr(4,1:N))' (wr(1:N))],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingCleanN4.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(Hr(5,1:N))' (wr(1:N))],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);


%%
clear all;close all;clc;
fs = 125e6; T = 1/fs;
N = 2^6;
R = 5;
e = 0.85;
fp = (fs/R*e/2);

[Ord, Wp] = ellipord(e/R, (1/e)/R, 1, 60 );
[B, A] = ellip(Ord, 1, 60, fp/(fs/2));

[H, w] = freqz(B, A, R*N+1);

% expanded vectors
we = [-fliplr(w') w'];
% we = [we - 2*pi we we + 2*pi];
He = [fliplr(H') H'];
% He = [He He He];

% Aliasing Copies
% w centered around negative 2pi/R (-2/R, if normalized to fs/2)
wn1 = we - 2*pi/R;
% w centered around positive 2pi/R (2/R, if normalized to fs/2)
wp1 = we + 2*pi/R;
% w centered around negative 4pi/R (-4/R, if normalized to fs/2)
wn2 = we - 4*pi/R;
% w centered around positive 4pi/R (4/R, if normalized to fs/2)
wp2 = we + 4*pi/R;
% w centered around negative 6pi/R (6/R, if normalized to fs/2)
wn3 = we - 6*pi/R;
% w centered around positive 6pi/R (6/R, if normalized to fs/2)
wp3 = we + 6*pi/R;

%% Save to files
plotFile = 'iirAliasingZero.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' we'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingN2.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wn1'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingP2.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wp1'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingN4.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wn2'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingP4.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wp2'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingN6.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wn3'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);
plotFile = 'iirAliasingP6.csv';
fh = fopen(plotFile,'w'); 
if fh ~= -1
    fprintf(fh, '%s,%s\n', 'abs(H)', 'w');
    fclose(fh);
end
dlmwrite(...
    plotFile,...
    [abs(He)' wp3'],...
    '-append',...
    'delimiter', ',',...
    'newline', 'unix'...
);

%% Plot
figure;
plot(we,20*log10(abs(He)));
hold on;
plot(wn1,20*log10(abs(He)),'-r');
plot(wn2,20*log10(abs(He)),'-m');
plot(wp1,20*log10(abs(He)),'-c');
plot(wp2,20*log10(abs(He)),'-k');
%% Reference Lines
line([0 0],[-120,0],'Color','k');
line([1*pi/5 1*pi/5],[-120,0],'Color','k');
line([2*pi/5 2*pi/5],[-120,0],'Color','k');
line([3*pi/5 3*pi/5],[-120,0],'Color','k');
line([4*pi/5 4*pi/5],[-120,0]);