function recordData(x, samplingRate, path, freq)
    plotFile = sprintf('%s/r%d/%d.csv', path, 125e6 / samplingRate, freq);
    fh = fopen(plotFile,'w');
    if fh ~= -1
        fprintf(fh, '%s\n', 'x');
        fclose(fh);
    end
    dlmwrite(...
        plotFile,...
        x,...
        '-append',...
        'delimiter', ',',...
        'newline', 'unix'...
    );
end