# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0}]

# IP: bd/design_1/ip/design_1_clk_gen_0_0/design_1_clk_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_gen_0_0 || ORIG_REF_NAME==design_1_clk_gen_0_0}]

# IP: bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_0_1 || ORIG_REF_NAME==design_1_dds_compiler_0_1}]

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0}]

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1}]

# IP: bd/design_1/ip/design_1_axis_to_data_lanes_0_0/design_1_axis_to_data_lanes_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_to_data_lanes_0_0 || ORIG_REF_NAME==design_1_axis_to_data_lanes_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_1_1/design_1_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_1 || ORIG_REF_NAME==design_1_xlslice_1_1}]

# IP: bd/design_1/ip/design_1_xlslice_1_2/design_1_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_2 || ORIG_REF_NAME==design_1_xlslice_1_2}]

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2}]

# IP: bd/design_1/ip/design_1_xlslice_0_4/design_1_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_4 || ORIG_REF_NAME==design_1_xlslice_0_4}]

# IP: bd/design_1/ip/design_1_FIR_resized_0/design_1_FIR_resized_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FIR_resized_0 || ORIG_REF_NAME==design_1_FIR_resized_0}]

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0}]

# IP: bd/design_1/ip/design_1_xlslice_6_0/design_1_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_0 || ORIG_REF_NAME==design_1_xlslice_6_0}]

# IP: bd/design_1/ip/design_1_FIR_resized1_0/design_1_FIR_resized1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FIR_resized1_0 || ORIG_REF_NAME==design_1_FIR_resized1_0}]

# IP: bd/design_1/ip/design_1_cic_compiler_0_0/design_1_cic_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cic_compiler_0_0 || ORIG_REF_NAME==design_1_cic_compiler_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_6_1/design_1_xlslice_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_1 || ORIG_REF_NAME==design_1_xlslice_6_1}]

# IP: bd/design_1/ip/design_1_FIR_resized1_1/design_1_FIR_resized1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FIR_resized1_1 || ORIG_REF_NAME==design_1_FIR_resized1_1}]

# IP: bd/design_1/ip/design_1_xlslice_7_0/design_1_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_7_0 || ORIG_REF_NAME==design_1_xlslice_7_0}]

# XDC: bd/design_1/ip/design_1_fir_compiler_0_0/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_FIR_resized_0/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FIR_resized_0 || ORIG_REF_NAME==design_1_FIR_resized_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_FIR_resized_0/design_1_FIR_resized_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_FIR_resized1_0/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FIR_resized1_0 || ORIG_REF_NAME==design_1_FIR_resized1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_FIR_resized1_0/design_1_FIR_resized1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_cic_compiler_0_0/design_1_cic_compiler_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_FIR_resized1_1/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FIR_resized1_1 || ORIG_REF_NAME==design_1_FIR_resized1_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_FIR_resized1_1/design_1_FIR_resized1_1_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
